[package]
name = "japonfou"
version = "0.1.0"
edition = "2021"
authors = ["boris <boris.lok@outlok.com>"]

[lib]
path = "src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "japonfou"

[dependencies]
axum = "0.5.17"
config = "0.13.2"
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
