[package]
name = "japonfou"
version = "0.1.0"
edition = "2021"
authors = ["boris <boris.lok@outlok.com>"]

[lib]
path = "src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "japonfou"

[dependencies]
anyhow = "1.0.66"
axum = "0.6.0-rc.4"
axum-extra = "0.4.0-rc.3"
config = "0.13.2"
hyper = { version = "0.14.23", features = ["full"] }
once_cell = "1.16.0"
regex = "1.7.0"
rs-snowflake = "0.6.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
sqlx = { version = "0.6.2", features = ["uuid", "chrono", "runtime-tokio-rustls", "macros", "postgres", "migrate", "offline"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace", "request-id"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.2.2", features = ["v4"] }
validator = "0.16.0"

[dev-dependencies]
reqwest = { version = "0.11.12", features = ["json", "rustls-tls", "cookies"], default-features = false }
fake = "2.5.0"
